# Generated by Django 4.1.7 on 2023-03-04 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensor',
            old_name='discription',
            new_name='description',
        ),
    ]
